#!/bin/bash

echo "Files arranging process started."

for file in files/*; do
  filename=$(basename "$file")
  first_char=$(echo "$filename" | cut -c1 | tr '[:upper:]' '[:lower:]')

  if [ -d "$first_char" ]; then
    mv "$file" "$first_char/"
  fi

done

echo "Files arranging process completed."